### ISSUE TITLE
NPE in MainActivity

### ISSUE THREAD

**Issue by blinskey** [blinskey/greek-reference#124]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benlinskey.greekreference/com.benlinskey.greekreference.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5692)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.benlinskey.greekreference.MainActivity.a(Unknown Source)
at com.benlinskey.greekreference.MainActivity.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5541)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
... 11 more
```

**Comment by blinskey** [comment]
Deobfuscated stack trace:

```
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.benlinskey.greekreference/com.benlinskey.greekreference.MainActivity}:
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5692)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.benlinskey.greekreference.MainActivity.void checkTabletDisplayMode()(Unknown Source)
                                              void handleIntent(android.content.Intent)
                                              void onItemSelected(java.lang.String)
                                              void onNavigationDrawerItemSelected(int)
                                              void switchToMode(com.benlinskey.greekreference.Mode)
                                              void swapInFragments(android.app.Fragment,android.app.Fragment)
                                              void setLexiconFavoriteIcon(android.view.Menu)
                                              void access$000(com.benlinskey.greekreference.MainActivity,android.app.Fragment,android.app.Fragment)
at com.benlinskey.greekreference.MainActivity.void onCreate(android.os.Bundle)(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5541)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
... 11 more
```

**Comment by blinskey** [comment]
We need to fix our ProGuard settings so that we get useful stack traces here. See 4a7783d.
