### ISSUE TITLE
Null reference to AbstractLexiconListFragment

### ISSUE THREAD

**Issue by blinskey** [blinskey/greek-reference#146]
```
java.lang.NullPointerException
at com.benlinskey.greekreference.views.MainActivity.getSelectedLexiconId(MainActivity.java:290)
at com.benlinskey.greekreference.presenters.LexiconPresenter.setLexiconFavoriteIcon(LexiconPresenter.java:91)
at com.benlinskey.greekreference.presenters.LexiconPresenter.onCreateOptionsMenu(LexiconPresenter.java:49)
at com.benlinskey.greekreference.views.MainActivity.onCreateOptionsMenu(MainActivity.java:148)
at android.app.Activity.onCreatePanelMenu(Activity.java:2538)
at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5137)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by blinskey** [comment]
Caused by a null AbstractLexiconListFragment. Compare to #149.
