### ISSUE TITLE
Crash when displaying Perseus webview

### ISSUE THREAD

**Issue by blinskey** [blinskey/greek-reference#148]
GR version: 1.9.2
Android version: 4.4
Device: Fonepad 7 (K012)

```
java.lang.NullPointerException
    at com.benlinskey.greekreference.views.detail.lexicon.LexiconDetailFragment.displayPerseusTool(LexiconDetailFragment.java:179)
    at com.benlinskey.greekreference.views.detail.lexicon.LexiconDetailFragment.onOptionsItemSelected(LexiconDetailFragment.java:147)
    at android.app.Fragment.performOptionsItemSelected(Fragment.java:1806)
    at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:1972)
    at android.app.Activity.onMenuItemSelected(Activity.java:2676)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:350)
    at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
    at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
    at android.support.v7.widget.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:44)
    at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:77)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:163)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:738)
    at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
    at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
    at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:187)
    at android.widget.AdapterView.performItemClick(AdapterView.java:299)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2949)
    at android.widget.AbsListView$3.run(AbsListView.java:3683)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:149)
    at android.app.ActivityThread.main(ActivityThread.java:5257)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by blinskey** [comment]
This appears to be a result of a lexicon parsing error. An exception containing the contents of the problematic entry will now be thrown when this happens. See the f247294 commit message for details and thoughts on future steps to address this problem.

**Comment by blinskey** [comment]
This appears to be a result of a lexicon parsing error. An exception containing the contents of the problematic entry will now be thrown when this happens. See the f247294 commit message for details and thoughts on future steps to address this problem.
