### ISSUE TITLE
Null reference to LexiconBrowseListFragment

### ISSUE THREAD

**Issue by blinskey** [blinskey/greek-reference#149]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benlinskey.greekreference/com.benlinskey.greekreference.views.MainActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.benlinskey.greekreference.views.MainActivity.selectLexiconItem(MainActivity.java:528)
    at com.benlinskey.greekreference.presenters.MainPresenter.getLexiconEntry(MainPresenter.java:135)
    at com.benlinskey.greekreference.presenters.MainPresenter.handleIntent(MainPresenter.java:62)
    at com.benlinskey.greekreference.views.MainActivity.onCreate(MainActivity.java:132)
    at android.app.Activity.performCreate(Activity.java:5442)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
    ... 11 more
```

**Comment by blinskey** [comment]
This appears to be a result of a lexicon parsing error. An exception containing the contents of the problematic entry will now be thrown when this happens. See the f247294 commit message for details and thoughts on future steps to address this problem.

**Comment by blinskey** [comment]
Caused by a null reference to a LexiconBrowseListFragment. Compare to #146.
