### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by blinskey** [blinskey/greek-reference#152]
```
java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
    at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1011)
    at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1111)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1839)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2259)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1964)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2259)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1964)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2259)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1964)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2259)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1964)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2259)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1964)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1970)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1420)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1918)
    at android.view.View.dispatchPointerEvent(View.java:7506)
    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3654)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3579)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4849)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4809)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4965)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4933)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4987)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
    at android.view.Choreographer.doCallbacks(Choreographer.java:579)
    at android.view.Choreographer.doFrame(Choreographer.java:546)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
    at android.os.Handler.handleCallback(Handler.java:800)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5409)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by blinskey** [comment]
This appears to be an upstream bug:

- [Android issue 175501](https://code.google.com/p/android/issues/detail?id=175501)
- [Android issue 60464](https://code.google.com/p/android/issues/detail?id=60464)
